### ISSUE TITLE
登录账号时出现的问题

### ISSUE THREAD

**Issue by Vixbob** [Rinacm/Pixeval#3]
错误日志:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Pixeval.Persisting.Identity.Parse(String password, TokenResponse token) in C:\NotSystem\Coding\projects\visualstudio\csharp\Pixeval\Persisting\Identity.cs:line 50
   at Pixeval.Persisting.Authentication.Authenticate(String name, String pwd) in C:\NotSystem\Coding\projects\visualstudio\csharp\Pixeval\Persisting\Authentication.cs:line 42
   at Pixeval.SignIn.Login_OnClick(Object sender, RoutedEventArgs e) in C:\NotSystem\Coding\projects\visualstudio\csharp\Pixeval\SignIn.xaml.cs:line 57
```
登录界面输入账号密码后，出现`Object reference not set to an instance of an object`的红色字样。
希望能够解决，十分感谢。

**Comment by Rinacm** [comment]
请问是使用的最新版本嘛

**Comment by Rinacm** [comment]
该bug是由于在登陆过程中无法与登录服务器连接所致，请检查是否遵循以下几点:
- 免代理模式可能在部分局域网(公司网，校园网)中不起作用，如果你的网络环境符合上述条件请尝试在设置中开启"关闭免代理模式"选项，同时本机启用代理以通过代理模式访问。
- 在关闭免代理模式时确保设置了可用的系统代理
请更新到最新release后再次根据以上建议尝试

**Comment by Rinacm** [comment]
刚刚发现还有一个原因是dns服务器无法连接，已经修改代码并设置了dns缓存，现在应该没问题了
